"""
Pydantic models for Quiet Eyes API.

Defines the data structures for business profiles, action cards,
and API request/response schemas.
"""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


# =============================================================================
# ENUMS
# =============================================================================

class Archetype(str, Enum):
    """
    Business archetype classification.
    Determines the type of insights and recommendations generated.
    """
    VISUAL = "Visual"      # Restaurants, fashion, design - image-driven
    EXPERT = "Expert"      # Lawyers, doctors, consultants - expertise-driven
    FIELD = "Field"        # Deliveries, repairs, cleaning - service area-driven
    MERCHANT = "Merchant"  # Retail, e-commerce - sales-driven


class CardType(str, Enum):
    """Type of action card - either an alert or opportunity."""
    ALERT = "alert"
    OPPORTUNITY = "opportunity"


# =============================================================================
# CORE MODELS
# =============================================================================

class ActionCard(BaseModel):
    """
    Represents an actionable insight card displayed in the user's feed.

    Cards are generated by the AI engine based on market analysis,
    competitor monitoring, or trend detection.
    """
    id: str = Field(..., description="Unique identifier for the card")
    type: CardType = Field(..., description="Card type: alert or opportunity")
    title: str = Field(..., description="Hebrew title for the card", max_length=100)
    description: str = Field(..., description="Hebrew description with context", max_length=500)
    action_button_text: str = Field(..., description="CTA button text in Hebrew", max_length=50)
    priority: int = Field(default=1, ge=1, le=5, description="Priority level 1-5")
    source: Optional[str] = Field(default=None, description="Source of the insight")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "card_001",
                "type": "alert",
                "title": "מתחרה העלה מחירים",
                "description": "פיצה 'נאפולי' העלתה מחירים ב-5 שקלים. הזדמנות למשוך לקוחות!",
                "action_button_text": "צפה בפרטים",
                "priority": 3,
                "source": "competitor_scan"
            }
        }


class WeeklyStat(BaseModel):
    """Weekly statistics for the business dashboard."""
    label: str = Field(..., description="Stat label in Hebrew")
    value: str = Field(..., description="Stat value")


class BusinessProfile(BaseModel):
    """
    Complete business profile including archetype classification,
    health metrics, and industry-specific data.
    """
    id: str = Field(..., description="Unique business identifier")
    name: str = Field(..., description="Business name")
    name_hebrew: str = Field(..., description="Business name in Hebrew")
    archetype: Archetype = Field(..., description="Business archetype")
    description: str = Field(..., description="Original business description")
    pulse_score: float = Field(..., ge=0, le=10, description="Business health score 0-10")
    pulse_change: str = Field(..., description="Change from previous period (e.g., '+0.5')")
    emoji: str = Field(..., description="Industry emoji")
    trending_topics: list[str] = Field(default_factory=list, description="Trending hashtags")
    weekly_stats: list[WeeklyStat] = Field(default_factory=list, description="Weekly statistics")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "biz_pizza_001",
                "name": "Pizza Restaurant",
                "name_hebrew": "פיצרייה",
                "archetype": "Merchant",
                "description": "I own a pizza place in Hadera",
                "pulse_score": 7.2,
                "pulse_change": "+0.3",
                "emoji": "🍕",
                "trending_topics": ["#פיצה", "#משלוחים", "#איטלקי"],
                "weekly_stats": [
                    {"label": "הזמנות", "value": "312"},
                    {"label": "לקוחות חדשים", "value": "45"}
                ]
            }
        }


# =============================================================================
# API REQUEST/RESPONSE MODELS
# =============================================================================

class AnalyzeBusinessRequest(BaseModel):
    """Request body for the /analyze-business endpoint."""
    description: str = Field(
        ...,
        description="Business description in any language",
        min_length=5,
        max_length=500
    )

    class Config:
        json_schema_extra = {
            "example": {
                "description": "I own a pizza place in Hadera"
            }
        }


class AnalyzeBusinessResponse(BaseModel):
    """Response from the /analyze-business endpoint."""
    profile: BusinessProfile = Field(..., description="Generated business profile")
    cards: list[ActionCard] = Field(..., description="Initial insight cards")
    success: bool = Field(default=True)
    message: str = Field(default="Business analyzed successfully")


class ScanCompetitorRequest(BaseModel):
    """Request body for the /scan-competitor endpoint."""
    competitor_name: str = Field(..., description="Name of the competitor", max_length=100)
    competitor_type: str = Field(..., description="Type of competitor business", max_length=100)
    business_id: Optional[str] = Field(default=None, description="Your business ID for context")

    class Config:
        json_schema_extra = {
            "example": {
                "competitor_name": "פיצה נאפולי",
                "competitor_type": "pizzeria",
                "business_id": "biz_pizza_001"
            }
        }


class ScanCompetitorResponse(BaseModel):
    """Response from the /scan-competitor endpoint."""
    card: ActionCard = Field(..., description="Generated alert card")
    scan_summary: str = Field(..., description="Summary of what was found")
    success: bool = Field(default=True)


class ErrorResponse(BaseModel):
    """Standard error response."""
    success: bool = Field(default=False)
    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(default=None, description="Detailed error info")
