-- ═══════════════════════════════════════════════════════════
-- Phase 2: Retention Layer — New Tables
-- ═══════════════════════════════════════════════════════════

-- Daily tasks generated by Claude AI
CREATE TABLE IF NOT EXISTS daily_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    minutes INTEGER DEFAULT 15,
    impact TEXT DEFAULT 'medium' CHECK (impact IN ('high', 'medium', 'low')),
    completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    generated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_tasks_business_date
    ON daily_tasks(business_id, generated_at DESC);

-- Health score history for trend tracking
CREATE TABLE IF NOT EXISTS health_score_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    score INTEGER NOT NULL DEFAULT 0,
    components JSONB,
    calculated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_health_score_history_business_date
    ON health_score_history(business_id, calculated_at DESC);

-- Re-engagement message log for rate limiting
CREATE TABLE IF NOT EXISTS re_engagement_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    message_type TEXT NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_re_engagement_log_business_date
    ON re_engagement_log(business_id, sent_at DESC);

-- Weekly reports tracking
CREATE TABLE IF NOT EXISTS weekly_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    week_start DATE NOT NULL,
    pdf_url TEXT,
    sent_at TIMESTAMPTZ,
    data JSONB
);

CREATE INDEX IF NOT EXISTS idx_weekly_reports_business_week
    ON weekly_reports(business_id, week_start DESC);

-- Add last_login_at to businesses if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'businesses' AND column_name = 'last_login_at'
    ) THEN
        ALTER TABLE businesses ADD COLUMN last_login_at TIMESTAMPTZ;
    END IF;
END $$;

-- Add pulse_score_data to businesses if not exists (for component breakdown)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'businesses' AND column_name = 'pulse_score_data'
    ) THEN
        ALTER TABLE businesses ADD COLUMN pulse_score_data JSONB;
    END IF;
END $$;
